language: node_js

stages:
  - name: after_success
    # require the branch name to be master (note for PRs this is the base branch name)
    if: branch = master

before_install:
  - node --version
  # Repo for Yarn
  - sudo apt-key adv --fetch-keys http://dl.yarnpkg.com/debian/pubkey.gpg
  - echo "deb http://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
  - sudo apt-get update -qq
  - sudo apt-get install -y -qq yarn

cache:
  yarn: true

install:
  - yarn install
  - yarn list

script:
  - yarn lint
  - travis_wait yarn test --ci --maxWorkers=2 --verbose --coverage --coverageReporters=text-lcov | yarn run coveralls # report coveralls status

after_success:
  - yarn publish-npm
